modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="examplemod"
version="0.1.0"
displayName="Example Mod"
authors="thebluetropics"
description="An Example Mod"

[[dependencies.examplemod]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.1-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    type="required"
    versionRange="1.20.6"
    ordering="NONE"
    side="BOTH"
